return {
	-- {
	-- 	"yetone/avante.nvim",
	-- 	event = "VeryLazy",
	-- 	lazy = false,
	-- 	version = false,
	-- 	opts = {
	-- 		provider = "copilot",
	-- 		copilot = {
	-- 			model = "claude-3.7-sonnet",
	-- 			max_tokens = 8000,
	-- 		},
	-- 		auto_suggestions_provider = "copilot",
	-- 	},
	-- 	build = "make",
	-- 	dependencies = {
	-- 		"nvim-treesitter/nvim-treesitter",
	-- 		"stevearc/dressing.nvim",
	-- 		"nvim-lua/plenary.nvim",
	-- 		"MunifTanjim/nui.nvim",
	-- 		"echasnovski/mini.pick",
	-- 		"nvim-telescope/telescope.nvim",
	-- 		"hrsh7th/nvim-cmp",
	-- 		"ibhagwan/fzf-lua",
	-- 		"nvim-tree/nvim-web-devicons",
	-- 		{
	--
	-- 			"HakonHarnes/img-clip.nvim",
	-- 			event = "VeryLazy",
	-- 			opts = {
	--
	-- 				default = {
	-- 					embed_image_as_base64 = false,
	-- 					prompt_for_file_name = false,
	-- 					drag_and_drop = {
	-- 						insert_mode = true,
	-- 					},
	--
	-- 					use_absolute_path = true,
	-- 				},
	-- 			},
	-- 		},
	-- 		{
	--
	-- 			"MeanderingProgrammer/render-markdown.nvim",
	-- 			opts = {
	-- 				file_types = { "markdown", "Avante" },
	-- 			},
	-- 			ft = { "markdown", "Avante" },
	-- 		},
	-- 	},
	-- },
	-- {
	-- 	"CopilotC-Nvim/CopilotChat.nvim",
	-- 	event = "BufRead",
	-- 	dependencies = {
	-- 		{ "github/copilot.vim" },
	-- 		{ "nvim-lua/plenary.nvim", branch = "master" },
	-- 	},
	-- 	build = "make tiktoken",
	-- 	opts = {
	-- 		model = "claude-3.7-sonnet",
	-- 		show_help = "yes",
	-- 		prompts = {
	-- 			EXPLAIN = {
	-- 				prompt = "/COPILOT_EXPLAIN コードの説明を行ってください。",
	-- 				system_prompt = "あなたは物事を説明するのが非常に得意です",
	-- 				mapping = "<leader>ccoe",
	-- 			},
	-- 			REFACTOR = {
	-- 				prompt = "/COPILOT_GENERATE コードのリファクタリングを行ってください。",
	-- 				system_prompt = "あなたはコードのリファクタリングが非常に得意です",
	-- 				mapping = "<leader>ccor",
	-- 			},
	-- 			REVIEW = {
	-- 				prompt = "/COPILOT_REVIEW コードのレビューを行ってください。",
	-- 				system_prompt = "あなたはコードのレビューが非常に得意です",
	-- 				mapping = "<leader>ccorv",
	-- 			},
	-- 			Optimize = {
	-- 				prompt = "/COPILOT_OPTIMIZE コードについて最適化してください",
	-- 				mapping = "<leader>co",
	-- 			},
	-- 		},
	-- 	},
	-- 	keys = {
	-- 		{
	-- 			"<leader>cco",
	-- 			"<cmd>:CopilotChat<CR>",
	-- 			{ noremap = true, silent = true },
	-- 		},
	-- 	},
	-- },
	{
		"github/copilot.vim",
		lazy = false,
		config = function()
			vim.g.copilot_node_command = "~/.asdf/shims/node"
		end,
	},
}
