#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export PATH=/opt/homebrew/bin:$PATH
export PATH=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby:$PATH
export PYENV_ROOT=/Users/iz/.pyenv
export PATH=$HOME/.nodebrew/current/bin:$PATH
export PATH="/Users/ryoji.kouno/.deno/bin:$PATH"

# Customize to your needs...
alias prezto-update="git pull && git submodule update --init --recursive"
alias ls="lsd -al"
alias vi="nvim" # this is benri

eval "$(gh completion -s zsh)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
fi

export EDITOR=vi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/ryoji.kouno/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/ryoji.kouno/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/ryoji.kouno/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/ryoji.kouno/google-cloud-sdk/completion.zsh.inc'; fi
export PATH=$HOME/.nodebrew/current/bin:$PATH

setopt prompt_cr
setopt prompt_sp
